version: '3.7'

services:
  mongo:
    image: mongo:5.0.6-focal
    container_name: mongodb_zemoga_back
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: zemoga_test_back
    image: nodejs
    container_name: nodejs_zemoga_back
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    volumes:
      - .:/home/node/app
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./.babelrc:/home/node/app/.babelrc
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - /home/node/app/node_modules
    expose:
      - '8080'
    ports:
      - '8080:8080'
    #command: tail -f /dev/null
    depends_on:
      - mongo
volumes:
  dbdata:
